feat: update toolkit and doc, support apigw app and instance
serverless-components/tencent-scf pull request #72
Opened 2021-07-19 05:09 UTC by wwwzbwcom

- 支持 API 网关绑定 APP
- 支持 API 网关指定独享实例
- 更新对应的文档

2021-07-19 06:47 UTC, yugasun requested changes

2021-07-19 06:47 UTC, yugasun commented on docs/configure.md
> +| id          | string | APP ID              |
这几个参数添加一下`必选` 列。

2021-07-19 06:48 UTC, yugasun commented
@wwwzbwcom 帮忙确认下集成测试为什么失败了，如果有问题也帮忙一起修改下

2021-07-28 17:06 UTC, wwwzbwcom commented on docs/configure.md
> +| id          | string | APP ID              |
done

2021-07-29 02:04 UTC, yugasun requested changes

2021-07-29 02:04 UTC, yugasun commented on example/web/src/scf_bootstrap
> -/var/lang/node12/bin/node app.js
删除 web 函数的入口文件是处于什么考虑？

2021-07-29 07:36 UTC, yugasun approved these changes

2021-07-30 03:26 UTC, merged

2021-07-30 03:26 UTC, slsplus commented
:tada: This PR is included in version 0.8.0 :tada:

The release is available on [GitHub release](https://github.com/serverless-components/tencent-scf/releases/tag/v0.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: